name: learnflutter
description: My first flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  logger: ^1.1.0
  get: ^4.6.5
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.2
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
